# Generated by Django 5.2.17 on 2026-08-24 16:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tension_arterielle', models.CharField(help_text='Ex. 120/80', max_length=15, verbose_name='tension artérielle')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='température (°C)')),
                ('poids', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='poids (kg)')),
                ('taille', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='taille (cm)')),
                ('frequence_cardiaque', models.PositiveSmallIntegerField(verbose_name='fréquence cardiaque (bpm)')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='patients.patient')),
                ('pris_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constantes_prises', to=settings.AUTH_USER_MODEL, verbose_name='pris par')),
            ],
            options={
                'verbose_name': 'constante',
                'verbose_name_plural': 'constantes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255)),
                ('symptomes', models.TextField(blank=True, verbose_name='symptômes')),
                ('diagnostic', models.TextField()),
                ('conduite_a_tenir', models.TextField(blank=True, verbose_name='conduite à tenir')),
                ('date_consultation', models.DateTimeField(default=django.utils.timezone.now)),
                ('constante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='consultations.constante')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_medecin', to=settings.AUTH_USER_MODEL, verbose_name='médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('mention', models.CharField(blank=True, default='À renouveler uniquement sur avis médical.', max_length=255)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'ordonnance',
                'verbose_name_plural': 'ordonnances',
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_nom', models.CharField(max_length=120, verbose_name='médicament')),
                ('posologie', models.CharField(max_length=120)),
                ('duree_traitement', models.CharField(max_length=80, verbose_name='durée du traitement')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='consultations.ordonnance')),
            ],
            options={
                'verbose_name': "ligne d'ordonnance",
                'verbose_name_plural': "lignes d'ordonnance",
            },
        ),
    ]
