# Generated by Django 5.2.17 on 2026-08-24 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_medecin', to=settings.AUTH_USER_MODEL, verbose_name='réalisé par'),
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(verbose_name='date et heure')),
                ('motif', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('HONORE', 'Honoré'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_medecin', to=settings.AUTH_USER_MODEL, verbose_name='médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
                'ordering': ['date_heure'],
            },
        ),
    ]
