# Generated by Django 5.2.17 on 2026-08-24 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(editable=False, help_text='Généré automatiquement : PAT-AAAA-XXXX', max_length=20, unique=True, verbose_name='numéro de dossier')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80, verbose_name='prénom')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('INCONNU', 'Inconnu')], default='INCONNU', max_length=8)),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('antecedent_medicaux', models.TextField(blank=True, verbose_name='antécédents médicaux')),
                ('antecedent_chirurgicaux', models.TextField(blank=True, verbose_name='antécédents chirurgicaux')),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_crees', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='patients_pa_nom_d8dfda_idx'), models.Index(fields=['numero_dossier'], name='patients_pa_numero__169aca_idx')],
            },
        ),
    ]
